baseURL = "https://hngmcast.netlify.app/"
languageCode = "en-gb"
title = "Slack Hunger Games Podcast"
theme = "hyde"

[markup]
    defaultMarkdownHandler = "blackfriday"

[blackfriday]
  extensions = ["hardLineBreak"]

[params]
  themeColor = "theme-base-0c"
  layoutReverse = true
  description = "Slack Hunger Games Podcast"
  author = "Nama"
  category = "Leisure"
  subcategory = "Video Games"
  year = "2022"
