baseURL = "harvestseason.club" # TODO: Buy domain
languageCode = "en-gb"
title = "The Harvist Season"
theme = "hyde"

[params]
  themeColor = "theme-base-0f"
  layoutReverse = true
  description = "A podcast about farming sims"