baseURL = "https://harvestseason.club/"
languageCode = "en-gb"
title = "The Harvest Season"
theme = "hyde"

[blackfriday]
  extensions = ["hardLineBreak"]

[params]
  themeColor = "theme-base-0f"
  layoutReverse = true
  description = "A podcast about farming simulators"
  creator = "TheScotBot"
  author = "Al McKinlay and Raschelle Dellaney"
