baseURL = "https://www.harvestseason.club/"
languageCode = "en-gb"
title = "The Harvest Season"
theme = "hyde"

[params]
  themeColor = "theme-base-0f"
  layoutReverse = true
  description = "A podcast about farming sims"